### ISSUE TITLE
write article about how to write a scratch 3 extension (in Chinese)

### ISSUE THREAD

**Issue by gasolin** [gasolin/scratch3-internet#3]
some references

kittenblock的文件已經寫得很清楚
https://kittenbot.readthedocs.io/zh_CN/latest/kittenblock/advanced/index.html

生成器的教學文件https://kittenbot.readthedocs.io/zh_CN/latest/kittenblock/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%8F%92%E4%BB%B6%E7%94%9F%E6%88%90%E7%B3%BB%E7%BB%9F.html#id2

kittenblock提供的生成器所產生的code需要稍作修改，才能適用於一般版的scratch 3

**Comment by justinahsu** [comment]
會加入 https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md 中文翻譯資料。（目前正在學習使用github）

中文翻譯檔位於：https://github.com/justinahsu/scratch-vm/blob/develop/docs/extensions.md

**Comment by justinahsu** [comment]
國全老師提供的資料。

https://blog.everlearn.tw/scratch3/%E9%96%8B%E7%99%BC%E4%BD%A0%E7%9A%84%E7%AC%AC%E4%B8%80%E5%80%8B-scratch-3-0-extension

https://blog.everlearn.tw/scratch3/%E5%88%A9%E7%94%A8-scratch-vm-%E9%96%8B%E7%99%BC-scratch-3-0-extension

**Comment by gasolin** [comment]
https://blog.gasolin.idv.tw/2019/11/19/scratch3-internet/
